apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: ''
  name: parksmap-zhongxin
  namespace: gaolan-zhongxin
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - parksmap-zhongxin
