commonLabels:
  layer: zhongxin
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- route.yaml
configMapGenerator:
- name: parksmap-data-2
  files:
  - application.properties
secretGenerator:
- name: parksmap-secret
  literals:
  - username=admin
  - password=admin123
images:
- name: quay.io/openshiftroadshow/parksmap
  newName: quay.io/openshiftroadshow/parksmap
  newTag: latest