resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- configmap-2.yaml
- secret.yaml
- route.yaml
images:
- name: quay.io/williamsrlin/parksmap
  newName: quay.io/openshiftroadshow/parksmap
  newTag: latest